# Generated by Django 2.1.3 on 2019-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseagenda',
            name='courseKey',
            field=models.IntegerField(),
        ),
    ]
