# Generated by Django 2.1.3 on 2019-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classAPI', '0002_auto_20190908_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseagenda',
            name='courseKey',
            field=models.CharField(max_length=50),
        ),
    ]
