# Generated by Django 2.1.3 on 2019-09-22 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classAPI', '0003_auto_20190908_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseSubmissionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('submission', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('userKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseagenda',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
