# Generated by Django 2.1.3 on 2019-12-01 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classAPI', '0004_auto_20190922_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubmissiontext',
            name='course',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='coursesubmissiontext',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
